[package]
name = "rens"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = "1.6.2"
ens-normalize = { path = "../ens-normalize" }
thiserror = "2.0.18"
tokio = { version = "1.49.0", features = ["full"] }
